export type Product = {
  slug: string; name: string; category: "Shaped" | "Unshaped"; short: string; description: string; grades: string[]; image: string; datasheet?: { label: string; url: string };
};
export const products: Product[] = [
  { slug: "lightweight-bricks", name: "Lightweight bricks", category: "Shaped", short: "Insulation for demanding thermal environments.", description: "A range of insulating refractory bricks for applications where thermal insulation and low weight are priorities. Discuss your operating conditions with our team to select the appropriate grade.", grades: ["BLW2301", "BLW3001", "BLW4001", "BLW4201", "BLW4501", "BLW5001", "BLW6001", "BLW6301", "BLW6801", "BLW7001"], image: "/images/production.jpg", datasheet: { label: "BLW2301 technical datasheet", url: "https://asfourmr.com/wp-content/uploads/2025/02/BLW2301.pdf" } },
  { slug: "dense-alumina-bricks", name: "Dense alumina bricks", category: "Shaped", short: "Fireclay and high-alumina refractory solutions.", description: "Our dense brick range includes fireclay and high-alumina products in a selection of grades. Share your furnace design and process requirements for guidance on material selection.", grades: ["BFC30", "BFC35", "BFC38", "BFC40", "BFC42", "BFC43", "BHA45", "BHA50", "BHA60", "BHA70", "BHA80", "BHA85", "BHA90"], image: "/images/production.jpg", datasheet: { label: "BHA45 technical datasheet", url: "https://asfourmr.com/wp-content/uploads/2024/08/BHA45.pdf" } },
  { slug: "cordierite-mullite-bricks", name: "Cordierite–mullite bricks", category: "Shaped", short: "Specialist compositions for your thermal process.", description: "Cordierite–mullite refractory bricks are available in a range of compositions. Our team can help match your application to a suitable product specification.", grades: ["BCM3501", "BCM4001", "BCM4201", "BCM4502", "BCM5001", "BCM6001"], image: "/images/kiln.jpg" },
  { slug: "chemical-bond-bricks", name: "Chemically bonded bricks", category: "Shaped", short: "Alternative bonding systems for specific requirements.", description: "Chemically bonded refractory bricks offer additional options within the shaped range. Contact our specialists to discuss process compatibility and grade selection.", grades: ["BCB5201", "BCB6001", "BCB6401", "BCB8001"], image: "/images/production.jpg" },
  { slug: "acid-resistant-bricks", name: "Acid-resistant bricks", category: "Shaped", short: "Materials selected for chemically demanding conditions.", description: "Acid-resistant bricks are available in multiple grades for specialist applications. Provide details of the chemical environment and operating conditions to establish suitability.", grades: ["BAR2501", "BAR3301", "BAR3501", "BAR4001"], image: "/images/kiln.jpg" },
  { slug: "castables", name: "Refractory castables", category: "Unshaped", short: "Versatile materials. Application-led specifications.", description: "Choose from lightweight, low-cement, traditional alumina, and cordierite castables. Our team supports material selection around the requirements of your installation.", grades: ["Lightweight castables · CLW", "Low-cement castables · LCC", "Traditional castables · TCC", "Cordierite castables · LCM"], image: "/images/bricks.jpg" },
  { slug: "mortars", name: "Refractory mortars", category: "Unshaped", short: "The right connection between refractory components.", description: "Our mortar range includes heat-setting, air-setting, acid-resistant, and phosphate-bonded materials. Discuss the brick grade and installation requirements with our team.", grades: ["Heat-setting · MHS", "Air-setting · MAS", "Acid-resistant · MAR", "Phosphate-bonded · MPR"], image: "/images/bricks.jpg" },
  { slug: "chamotte", name: "Chamotte", category: "Unshaped", short: "Raw materials for refractory and ceramic production.", description: "Chamotte is supplied across refractory, lightweight, and sanitary-ware ranges. Ask our sales team about available particle sizes and compositions for your production process.", grades: ["Refractory chamotte · CHR", "Lightweight chamotte · LWC", "Sanitary-ware chamotte · CHS"], image: "/images/hero.jpg" },
  { slug: "calcined-bauxite", name: "Calcined bauxite", category: "Unshaped", short: "A selection of particle sizes for your process.", description: "Calcined bauxite is offered in fine and aggregate sizes to meet a range of production requirements. Request current technical specifications and availability from our team.", grades: ["90 μm · C.B 90011", "500 μm · C.B 90012", "0–1 mm · C.B 90013", "1–3 mm · C.B 90014", "3–5 mm · C.B 90015"], image: "/images/bricks.jpg" },
];
export const industries = [
  { name: "Iron & steel", slug: "iron-steel", text: "Refractory and insulation solutions for steel production and casting.", icon: "steel" },
  { name: "Cement & lime", slug: "cement-lime", text: "Refractory material selection for demanding kiln operations.", icon: "cement" },
  { name: "Glass & ceramics", slug: "glass-ceramics", text: "Materials for thermal processes in glass and ceramic manufacturing.", icon: "glass" },
  { name: "Aluminium & non-ferrous", slug: "aluminium", text: "Refractory solutions developed around metal processing requirements.", icon: "aluminium" },
  { name: "Chemicals & petrochemicals", slug: "chemicals", text: "Application-led solutions for industrial processing environments.", icon: "chemical" },
  { name: "Power & other industries", slug: "power", text: "Serving power generation, sugar, coke ovens, and refractory manufacturing.", icon: "power" },
];
