import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Plus } from "lucide-react";
import { Hero } from "@/components/hero";
import { ProductPreview } from "@/components/product-explorer";
import { IndustryIcon } from "@/components/industry-icon";
import { ContactBanner } from "@/components/site-footer";
import { industries } from "@/lib/data";
export default function Home() {
  return <>
    <Hero />
    <section className="intro-section section-pad" id="introduction"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="section-number">01 /</span> THE ASFOUR DIFFERENCE</p><h2>STRONG FOUNDATIONS.<br /><span className="text-blue">GREATER POSSIBILITIES.</span></h2></div><div className="intro-copy"><p>Behind every great industry are materials that can take the heat. We make them.</p><p>Since 1982, Asfour has brought together manufacturing expertise and a deep understanding of industrial needs to deliver refractory solutions that go further.</p><Link href="/about" className="text-link">Get to know Asfour <ArrowUpRight size={20} /></Link></div></div><div className="fact-strip"><div><strong>40<span>+</span></strong><span>YEARS OF EXPERIENCE</span></div><div><strong>30<span>+</span></strong><span>COUNTRIES SERVED</span></div><div><strong>100,000<span>+</span></strong><span>TONS ANNUAL CAPACITY</span></div><div><strong>500<span>+</span></strong><span>PEOPLE. ONE COMMITMENT.</span></div></div></div></section>
    <section className="products-section section-pad"><div className="container"><div className="section-heading compact"><div><p className="eyebrow"><span className="section-number">02 /</span> OUR PRODUCTS</p><h2>THE RIGHT MATERIAL.<br />FOR EVERY CHALLENGE.</h2></div><Link className="button button-outline" href="/products">Explore the range <ArrowUpRight size={19} /></Link></div><ProductPreview /></div></section>
    <section className="industries-section section-pad"><div className="container"><div className="section-heading compact"><div><p className="eyebrow"><span className="section-number">03 /</span> INDUSTRIES WE SERVE</p><h2>WHERE INDUSTRY WORKS,<br />WE WORK.</h2></div><p className="heading-aside">Different processes. Different pressures.<br />One partner who understands your industry.</p></div><div className="industry-home-grid">{industries.slice(0, 4).map((industry, i) => <Link key={industry.slug} className="industry-home-item" href={`/industries#${industry.slug}`}><div className="industry-top"><IndustryIcon type={industry.icon} /><span>0{i + 1}</span></div><h3>{industry.name}</h3><div className="industry-bottom"><span>Explore solutions</span><ArrowUpRight size={24} /></div></Link>)}</div><Link href="/industries" className="text-link light-link">Discover all industries <ArrowRight size={18} /></Link></div></section>
    <section className="research-section section-pad"><div className="container research-grid"><div className="research-visual"><Image src="/images/research.jpg" alt="Research and development at Asfour" fill sizes="(max-width: 760px) 100vw, 50vw" /><div className="image-corner"><Plus size={26} /> CONSTANTLY DEVELOPING.<br />ALWAYS MOVING FORWARD.</div></div><div className="research-copy"><p className="eyebrow"><span className="section-number">04 /</span> RESEARCH & DEVELOPMENT</p><h2>TODAY’S EXPERTISE.<br />TOMORROW’S<br /><span className="text-blue">SOLUTIONS.</span></h2><p>Better materials start with better questions. Our research and development facilities help us evolve our products around the changing needs of your industry.</p><Link href="/research" className="text-link">Inside our approach <ArrowUpRight size={19} /></Link></div></div></section>
    <section className="partners"><div className="container"><p className="eyebrow">IN GOOD COMPANY. TRUSTED BY INDUSTRY.</p><div className="partner-logos">{[["cemex", "Cemex"], ["lafarge", "Lafarge"], ["beshay", "Beshay Steel"], ["duravit", "Duravit"], ["flsmidth", "FLSmidth"]].map(([file, alt]) => <div key={file}><Image src={`/images/${file}.png`} alt={alt} width={160} height={90} /></div>)}</div></div></section>
    <ContactBanner />
  </>;
}
