"use client";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, ArrowRight, Search, X } from "lucide-react";
import { products } from "@/lib/data";

export function ProductPreview() {
  const [category, setCategory] = useState<"Shaped" | "Unshaped">("Shaped");
  return <div className="product-preview"><div className="product-preview-image"><Image src={category === "Shaped" ? "/images/production.jpg" : "/images/bricks.jpg"} alt={category === "Shaped" ? "Asfour refractory production" : "Asfour bulk refractory materials ready for delivery"} fill sizes="(max-width: 760px) 100vw, 45vw" /><span className="image-tag">MATERIALS THAT MAKE A DIFFERENCE</span></div><div className="product-preview-content"><div className="product-tabs" role="group" aria-label="Product category">{(["Shaped", "Unshaped"] as const).map(item => <button key={item} aria-pressed={category === item} className={category === item ? "selected" : ""} onClick={() => setCategory(item)}>{item} products <span>0{item === "Shaped" ? 5 : 4}</span></button>)}</div><div className="product-rows">{products.filter(p => p.category === category).slice(0, 3).map((product, i) => <Link key={product.slug} href={`/products/${product.slug}`} className="product-row"><span className="row-number">0{i + 1}</span><div><h3>{product.name}</h3><p>{product.short}</p></div><ArrowUpRight size={24} /></Link>)}</div><Link href={`/products?category=${category}`} className="text-link">View all {category.toLowerCase()} products <ArrowRight size={18} /></Link></div></div>;
}
export function ProductCatalogue({ initialCategory = "All" }: { initialCategory?: string }) {
  const [category, setCategory] = useState(["Shaped", "Unshaped"].includes(initialCategory) ? initialCategory : "All");
  const [query, setQuery] = useState("");
  const filtered = products.filter(p => (category === "All" || p.category === category) && `${p.name} ${p.short} ${p.grades.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <div><div className="catalogue-controls"><div className="filter-buttons" role="group" aria-label="Filter products">{["All", "Shaped", "Unshaped"].map(item => <button key={item} onClick={() => setCategory(item)} className={category === item ? "selected" : ""} aria-pressed={category === item}>{item === "All" ? "All products" : item}</button>)}</div><label className="search-field"><Search size={19} /><input aria-label="Search products or grades" placeholder="Search products or grades…" value={query} onChange={e => setQuery(e.target.value)} />{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={16} /></button>}</label></div><p className="results-count" role="status">{filtered.length} product {filtered.length === 1 ? "family" : "families"}</p><div className="catalogue-grid">{filtered.map((p) => <Link className="catalogue-item" key={p.slug} href={`/products/${p.slug}`}><div className="catalogue-image"><Image src={p.image} alt={`${p.category} refractory production at Asfour`} fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw" /><span>{p.category}</span></div><div className="catalogue-item-title"><h2>{p.name}</h2><ArrowUpRight size={24} /></div><p>{p.short}</p><span className="catalogue-grade-count">{p.grades.length} {p.grades.length > 5 ? "grades" : "ranges"} available</span></Link>)}</div>{filtered.length === 0 && <div className="empty-state"><h2>No matching products</h2><p>Try a product family such as “bricks” or a grade such as “BLW2301”.</p><button className="button button-blue" onClick={() => {setCategory("All"); setQuery("");}}>Clear filters <ArrowRight size={18} /></button></div>}</div>;
}
